server:
  port: 8888
  servlet:
    context-path: /demo
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
    include-exception: true

spring:
  application:
    name: spring-boot-demo


debug: false
